# Generated by Django 4.0 on 2022-01-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cloths',
            fields=[
                ('cloths_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('cloths_name', models.CharField(max_length=200)),
                ('cloths_type', models.CharField(max_length=200)),
                ('cloths_details', models.CharField(max_length=200)),
                ('cloths_price', models.CharField(max_length=500)),
                ('cloths_image', models.FileField(upload_to='cloths_image')),
            ],
            options={
                'db_table': 'store',
            },
        ),
    ]
