# Generated by Django 4.0 on 2022-01-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.CharField(max_length=200)),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
