# Generated by Django 4.0 on 2022-01-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('contact_message', models.TextField()),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
