# Generated by Django 4.0 on 2022-01-24 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cloth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cloths'),
        ),
    ]
