# Generated by Django 4.0 on 2022-01-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloths', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloths',
            name='flight_way',
        ),
    ]
